name: Process Age Range
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  process:
    runs-on: ubuntu-latest  # Ubuntu işletim sistemi üzerinde çalışacak
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Kodu kontrol et

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Python versiyonunu belirle

      - name: Run the script
        run: |
          python main.py input.txt  # Python kodunu çalıştır

      - name: Commit and push the result
        run: |
          
          
          # Çıktıyı aralığınız.txt dosyasına yaz
          echo "$(python main.py input.txt)" > araliginiz.txt
          
          git add araliginiz.txt  # Dosyayı Git'e ekle
          git commit -m "Update age range result"  # Commit yap

          # GitHub Token ile kimlik doğrulaması yaparak push işlemini gerçekleştir
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ardatunali/finaldeneme.git
